baseurl = "/"
DefaultContentLanguage = "de"
title = "Terra Bodenbel√§ge | Freiburg-Opfingen"

enableRobotsTXT = true
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.de]
    locale = "de_DE"
    weight = 1

[menu]
  [[menu.main]]
    name = "Anfrage"
    identifier = "anfrage"
    weight = 290
    url = "/#anfrage"
  [[menu.main]]
    name = "Kontakt"
    identifier = "contact"
    weight = 300
    url = "#kontakt"
